baseURL = "https://nacdlow.com"
languageCode = "en-uk"
title = "Nacdlow builds the smart home system of the future."
theme = "nacdlow"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
			xHTML = true
